name: h2static
version: git
summary: Tiny static web server with TLS and HTTP/2 support
description:
  Static web server using the builtin Go http library.

  It supports HTTP/2 and TLS.
confinement: strict
grade: stable

apps:
  h2static:
    command: bin/h2static
    plugs:
      - home
      - network-bind
      - removable-media

parts:
  h2static:
    plugin: go
    source: .
    source-type: git
    go-importpath: github.com/albertodonato/h2static
    build-snaps:
      - go
    override-build: |
      set -e

      PATH="/snap/bin:$PATH"
      snapcraftctl build
