name: h2static
version: git
summary: Tiny static web server with TLS and HTTP/2 support
description: |
  Static web server using the builtin Go http library.

  It supports HTTP/2 and TLS.

  This snap provides both an "h2static" command that can be run by any user,
  with access to the user home directory, and a system-wide daemon.

  The daemon is configured with the following options:

  - listen

    the "address:port" for the service to listen on. The address can be omitted
    (e.g. ":8080") to bind all addresses.

    If this option empty or null, the service will not be started.

  - serve-path

    the directory to serve content from. it's set to $SNAP_COMMON if not
    specified.

    If the "removable-media" interface is connected, paths under /media can
    also be used.

  - disable-h2

    set to true to disable HTTP/2 support.

  - tls.cert, tls.key

    ASCII contents of the TLS certificate and key. If both are set, HTTPS
    support will be enabled.
license: LGPL-3.0+
confinement: strict
grade: stable
base: core18

apps:
  h2static:
    command: bin/h2static
    plugs:
      - home
      - network-bind
      - removable-media

  daemon:
    command: bin/daemon
    daemon: simple
    plugs:
      - network-bind
      - removable-media

hooks:
  configure: {}

parts:
  h2static:
    plugin: go
    source: .
    source-type: git
    go-importpath: github.com/albertodonato/h2static

  daemon-wrapper:
    plugin: dump
    source: .
    organize:
      daemon.wrapper: bin/daemon
    prime:
      - bin/daemon
