name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2

    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: "1.18"

    - name: Vet
      run: |
        go vet ./...

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2

    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: "1.18"

    - name: Install dependencies
      run: |
        go get golang.org/x/lint/golint

    - name: Lint
      run: |
        golint ./...

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.16"
          - "1.17"
          - "1.18"
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2

    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Test
      run: |
        go test ./...
